---
title: "k means clustering"
author: "Sai Sree Pulimamidi"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r}
library(readr)
Pharmaceuticals <- read_csv("C:/users/91773/Desktop/Pharmaceuticals.csv")
View(Pharmaceuticals)
```
## installing libraries

```{r}
library(ggplot2)
library(factoextra)
library(flexclust)
library(cluster)
library(tidyverse)
summary(Pharmaceuticals)

#Task 1
#Use only the numerical variables (1 to 9) to cluster the 21 firms. 
#Justify the various choices #made in conducting the cluster analysis, 
#such as weights for different variables, the specific 
#clustering the algorithm(s) used,number of clusters formed, and so on. 
R <- na.omit(Pharmaceuticals)
R
row.names <- R[,1]
Pharmaceuticals1 <-  R[,3:11]
head(Pharmaceuticals1)
Pharmaceuticals2 <- scale(Pharmaceuticals1)
head(Pharmaceuticals2)
fviz_nbclust(Pharmaceuticals2, kmeans, method = "wss") +
  labs(subtitle = "Elbow Method")
fviz_nbclust(Pharmaceuticals2, kmeans, method = "silhouette") + labs(subtitle = "Silhouette Method")
fviz_nbclust(Pharmaceuticals2, kmeans, method = "gap_stat") + labs(subtitle = "Gap Stat Method")
```
```{r}
set.seed(64060)
k5 <- kmeans(Pharmaceuticals2, centers = 5, nstart = 25)
k5 $centers
fviz_cluster(k5, data = Pharmaceuticals2)
k5

Fitting <- kmeans(Pharmaceuticals2,5)
aggregate(Pharmaceuticals2,by = list(Fitting$cluster), FUN = mean)
Pharmaceuticals3 <- data.frame(Pharmaceuticals2,Fitting$cluster)
Pharmaceuticals3


```


```{r}

#Task 2

#using cluster formation to interpret the clusters in relation to the numerical variables.

aggregate(Pharmaceuticals2, by = list(Fitting$cluster), FUN = mean)
Pharmacy <- data.frame(Pharmaceuticals2,k5$cluster)
Pharmacy

#CLuster 1:- JNJ, MRK, GSK, PFE
#Cluster 1: Highest Market_Cap and lowest Beta/PE Ratio
#Cluster 2:- AHM, WPI, AVE
#Cluster 2: Highest Revenue Growth and lowest PE/Asset Turnover Ratio
#Cluster 3:- CHTT, IVX, MRX, ELN
#Cluster 3: Highest Beta/leverage/Asset Turnover Ratio and lowest 
#Net_Profit_Margin, PE ratio and Market#Cluster
#Cluster 4:- AGN,BAY, PHA
#Cluster 4: Highest PE ratio and lowest Leverage/Asset_Turnover
#Cluster 5:- ABT, WYE, AZN, SGP, BMY, NVS, LLY
#Cluster 5: Highest Net_Proft_Margin and lowest Leverage
```


```{r}

#Task3
#Is there a pattern in the clusters with respect to the numerical 
#variables (10 to 12)? (those \n #not used in forming the clusters)
RD <- Pharmaceuticals[12:14] %>% mutate(Clusters=k5$cluster)
ggplot(RD, mapping = aes(factor(Clusters), fill =Median_Recommendation))+geom_bar(position='dodge')+labs(x ='Clusters')
ggplot(RD, mapping = aes(factor(Clusters),fill = Location))+
  geom_bar(position = 'dodge')+labs(x ='Clusters')
ggplot(RD, mapping = aes(factor(Clusters),fill = Exchange))+geom_bar(position = 'dodge')+
  labs(x ='Clusters')
#The above graphs indicates that there is a slim pattern in the clusters.

#In Cluster 1,the firms are evenly distributed among AMEX,NASDAQ, and NYSE despite the fact that cluster 1 has a different Hold and Moderate Buy median, a different count from the US and Germany, and a distinct nation count.

#In Cluster 2,The medians for the cluster 2 are equally split between "Hold" and "Moderate Buy," and it is solely listed on the NYSE.

#In Cluster 3,the Moderate Buy and Sell medians for the NYSE-listed are equal, and it has a separate count for France, Ireland, and the US.

#In Cluster 4, the Hold median is the highest, followed by the Moderate Buy and Strong Buy medians, and the Hold median. They are listed on the NYSE and are from the US, the UK, and Switzerland.

#The Cluster 5 is distributed throughout the US and the UK, it is listed on the NYSE, and it has the same hold and mild buy medians.

```


```{r}


#TASK 4
#Provide an appropriate name for each cluster using any or all of the variables in the dataset.

#Cluster 1 :- Buy Cluster
#Cluster 2 :- Sceptical Cluster
#Cluster 3 :- Moderate Buy Cluster
#Cluster 4 :- Hold Cluster
#Cluster 5 :- High Hold Cluster 
```





